# Generated by Django 4.1.3 on 2023-02-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='Femenino', max_length=10)),
                ('domicilio', models.CharField(max_length=70)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='Femenino', max_length=10)),
                ('domicilio', models.CharField(max_length=70)),
                ('correo', models.EmailField(max_length=254)),
                ('cargo', models.CharField(choices=[('1', 'Tecnico Base'), ('2', 'Tecnico Medio'), ('3', 'Tecnico Senior')], default='Tecnico 1', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='planes',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=100)),
                ('velocidad', models.IntegerField()),
                ('tipo', models.TextField(choices=[('Fibra Optica', 'Fibra Optica'), ('Residencial', 'Residencial'), ('Coorporativo', 'Coorporativo')], default='Fibra Optica', max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='vehiculos',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=70)),
                ('modelo', models.CharField(max_length=75)),
            ],
        ),
    ]
