# Generated by Django 4.1.3 on 2023-01-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='Femenino', max_length=10)),
                ('domicilio', models.CharField(max_length=70)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='Femenino', max_length=10)),
                ('domicilio', models.CharField(max_length=70)),
                ('correo', models.EmailField(max_length=254)),
                ('cargo', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='planes',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('velocidad', models.CharField(choices=[('50', 'Basico'), ('100', 'Premiun'), ('200', 'Nitro')], default='50', max_length=10)),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vehiculos',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=70)),
                ('modelo', models.CharField(max_length=75)),
            ],
        ),
    ]
