# Generated by Django 4.1.3 on 2023-02-04 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.clientes')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.planes')),
            ],
        ),
    ]
