# Generated by Django 4.1.3 on 2023-01-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cargo',
            field=models.CharField(choices=[('1', 'Tecnico Base'), ('2', 'Tecnico Medio'), ('3', 'Tecnico Senior')], default='Tecnico 1', max_length=70),
        ),
    ]
