# Generated by Django 4.1.3 on 2023-02-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0002_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='id_plan',
            new_name='id_contrato',
        ),
    ]
