# Generated by Django 4.1.3 on 2023-02-08 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0003_rename_id_plan_contrato_id_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cargo',
            field=models.CharField(choices=[('1', 'Tecnico Base'), ('2', 'Tecnico Medio'), ('3', 'Tecnico Senior')], default='Tecnico Base', max_length=70),
        ),
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id_fra', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_t', models.CharField(choices=[('Instalacion', 'Instalar'), ('Desintalacion', 'Desinstalar'), ('Cambio de domicio', 'Mudansa')], default='Instalar', max_length=20)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.contrato')),
            ],
        ),
    ]
