# Generated by Django 4.1.3 on 2023-02-17 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0004_alter_personal_cargo_infraestructura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.infraestructura')),
                ('personal', models.ManyToManyField(to='isp.personal')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.vehiculos')),
            ],
        ),
    ]
